x-klipper-simulavr: &klipper-simulavr
  depends_on:
    init:
      condition: service_completed_successfully
    simulavr:
      condition: service_started
  privileged: true
  command: -I printer_data/run/klipper.tty -a printer_data/run/klipper.sock printer_data/config/printer-simulavr.cfg -l printer_data/logs/klippy.log
  volumes:
    - ./config:/opt/printer_data/config
    - run:/opt/printer_data/run
    - gcode:/opt/printer_data/gcodes
    - log:/opt/printer_data/logs
    - /dev:/dev

services:
  ## simulavr
  simulavr:
    image: simulavr
    restart: unless-stopped
    build:
      context: docker/klipper
      target: build-simulavr
      args: 
        VERSION: master
    privileged: true
    volumes:
      - /dev:/dev
      - run:/opt/printer_data/run
    labels:
      org.prind.service: simulavr
  
  ## Reconfigure Klipper service for simulavr
  klipper:
    <<: *klipper-simulavr

  klipper-priv:
    <<: *klipper-simulavr
